package com.sapienter.jbilling.server.metafields;

public enum MetaFieldType {

    ORGANIZATION,
    ADDRESS1,
    ADDRESS2,
    CITY,
    STATE_PROVINCE,
    POSTAL_CODE,
    COUNTRY_CODE,

    FIRST_NAME,
    LAST_NAME,
    INITIAL,
    TITLE,

    PHONE_COUNTRY_CODE,
    PHONE_AREA_CODE,
    PHONE_NUMBER,

    FAX_COUNTRY_CODE,
    FAX_AREA_CODE,
    FAX_NUMBER,

    EMAIL,
    
    BANK_NAME,
    BANK_ACCOUNT_NUMBER,
    BANK_ROUTING_NUMBER,
    BANK_ACCOUNT_TYPE,
    
    DATE,
    CHEQUE_NUMBER,
    
    PAYMENT_CARD_NUMBER,
    GATEWAY_KEY,
    CC_TYPE,
    
    ABAR_NUMBER,
    CREDIT_MEMO_REMARKS,
    
    CC_CARDHOLDER_NAME,
    CC_CREDIT_CARD_NUMBER,
    CC_EXPIRY_DATE,
    CC_CVV,
    CC_STREET,
    CC_CITY,
    CC_STATE,
    CC_ZIPCODE
}
